#!/bin/bash

/wp_setup

#echo "env[MARIADB_PASSWORD] = '$MARIADB_PASSWORD'" >> /etc/php/7.4/fpm/pool.d/www.conf
cat > /etc/php/7.4/fpm/pool.d/runtime_env.conf << ENV
[www]
env[MARIADB_PASSWORD] = '$MARIADB_PASSWORD'
ENV

exec php-fpm7.4 -F
