#!/bin/bash

# wp core install --url="$WP_URL" --title="$WP_TITLE" --admin_user="$WP_ADMIN_USER" \
# 	--admin_password="$WP_ADMIN_PASSWORD" --admin_email="$WP_ADMIN_EMAIL" --skip-email --allow-root
# 
# wp plugin update --all --allow-root
# 
# wp user create $WP_DUMMY_USER $WP_DUMMY_EMAIL --role=author --user_pass=$WP_DUMMY_PASSWORD --allow-root

if [ ! -f /var/www/website/.wp-init ]; then
	sleep 5 # wait for db to set up
	#wp core download --allow-root

	#wp core install --url=foo.com --title="WPage" --admin_user="nimda" \
	#	--admin_password="$ADMIN_PASSWORD" --admin_email="najacque@student.s19.be" --skip-email --allow-root
	wp core install --url="localhost" --title="WPage" --admin_user="nimda" \
		--admin_password="$ADMIN_PASSWORD" --admin_email="najacque@student.s19.be" --skip-email --allow-root

	wp plugin update --all --allow-root

	wp user create alice alice@foomail.bar --role=author --user_pass="$ALICE_PASSWORD" --allow-root

	touch /var/www/website/.wp-init
fi

#wp user create $WP_DUMMY_USER $WP_DUMMY_EMAIL --role=author --user_pass=$WP_DUMMY_PASSWORD --allow-root
