#!/bin/bash
service mariadb start

mariadb << SQL
CREATE DATABASE wordpress;
CREATE USER 'wordpress'@'wordpress.%_dockernet' IDENTIFIED by '$MARIADB_PASSWORD';
GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress'@'wordpress.%_dockernet';

SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$ROOTDB_PASSWORD');

FLUSH PRIVILEGES;
SQL

sleep 1
service mariadb stop

#exec mysqld_safe
exec mysqld &> /dev/null
